### ISSUE TITLE
T-Shirt Restocking

### ISSUE THREAD

**Issue by siennathesane** [dotnet-foundation/wg-marketing#1]
I was wondering if there was a plan for these [.NET Source t-shirts](https://stores.kotisdesign.com/dotnetfoundation/apparel-unisex/net-source-unisex-tee/61785) to be restocked?

**Comment by BethMassi** [comment]
We're going to take a look at the whole store this quarter and see if we can get some new items based on the new branding in there.

**Comment by BethMassi** [comment]
Update here. We'll have some new lovely items in the store for .NET Conf Nov 10th.

**Comment by tonyqus** [comment]
The T-shirt looks nice! love it

**Comment by BethMassi** [comment]
Forgot to update! We have a LOT of new items. See:
https://store.dotnetfoundation.org/dotnetfoundation/accessories
https://store.dotnetfoundation.org/dotnetfoundation/apparel-unisex
