### ISSUE TITLE
Unable to update speaker profile on new DNF website

### ISSUE THREAD

**Issue by codehippie1** [dotnet-foundation/wg-marketing#10]
A current speaker in this speaker list https://dotnetfoundation.org/community/speakers should be able to update their speaker profile. Currently there are no mechanisms to authenticate the user/member to safely do this.

**Comment by nicoleabuhakmeh** [comment]
A discussion around this was held and a way to contact someone on the Marketing team to update a speaker profile has been added to the individual pages.   We will revisit this action if it becomes overused. 
Text added: 
Is there anything here you would like updated? If so, please reach out to us at [marketing@dotnetfoundation.org](https://dotnetfoundation.org/home)

**Comment by codehippie1** [comment]
@nicoleabuhakmeh There could be a minor thing here. We may request the user to reach out from the "registered email" address (The email address while joining DNF/on speaker profile)

Otherwise, impersonators could reach out and might successfully modify speaker bio of other folks.
This is in light of issue #5 
Just a thought.
