### ISSUE TITLE
Request Authorization of .NET Foundation

### ISSUE THREAD

**Issue by tonyqus** [dotnet-foundation/wg-marketing#11]
Hi Team,

Since I'm going to hold an big .NET event in Shanghai, China in Q4, 2023, I'd like to check how I can get authorization from .NET foundation team. The event will be called .NET Open Conf. Since I'd like to emphasis the Openness of .NET and the ecosystem,  .NET foundation's authorization is needed to allow me say that this event is held by .NET foundation instead of Microsoft. 

Please let me know what kind of event info I shall provide from my side and I do need this official authorization. 

Thank you!

**Comment by tonyqus** [comment]
Can someone reply this ticket?

**Comment by Jaures-beinjamin** [comment]
Hi
