### ISSUE TITLE
Organize Event in School

### ISSUE THREAD

**Issue by sansob** [dotnet-foundation/wg-marketing#2]
My name is Hasan. I am a dot Net developer from Jakarta, Indonesia.

I intend to hold a dot net event, dot net introduction for vocational high school students in one of the small cities in Indonesia

They have just learned programming, and can turn the dot net into learning for them.

The event will be held on May 2, 2020 at SMK Tunas Harapan Pati with students as participants in this Workshop.

I hope Dot Net Foundation can help organize this workshop. 

Thank you

Regards

Hasan Shobri

**Comment by mhmohona** [comment]
I had organized programming camp for school kids.

**Comment by mhmohona** [comment]
I have organized programming camp for school kids as a part of Hours of code. I will highly recommend you to go through[ Hour of Code](https://hourofcode.com/us/learn) material. 
Best wishes! 

@BethMassi is it possible to have a page on the foundation's website or a repo where event organizers' can show off what they organized? Then others could see, get inspired and also learn from them.

**Comment by BethMassi** [comment]
Hi folks! That's awesome. This is probably a better discussion to have in the [outreach team](https://github.com/orgs/dotnet-foundation/teams/outreach) or on the [events repo](https://github.com/dotnet-foundation/events/issues) we just created. If you're looking to create some content (or just promote some) take a look at the [content repo](https://github.com/dotnet-foundation/content).
