### ISSUE TITLE
Proposal process feedback

### ISSUE THREAD

**Issue by BethMassi** [dotnet-foundation/wg-marketing#3]
We need to define how marketing proposals get submitted and reviewed. The idea is we create an issue template for the proposal process we started defining here: [Marketing Proposals](https://github.com/dotnet-foundation/wg-marketing/blob/master/proposals.md). 

These proposals are from our members to request funds to perform marketing activities and drive initiatives that align to our goals and priorities. 

- What are we looking for in the submission? What's our criteria besides cost?
- How are they reviewed by the committee? Proposed: Monthly at committee member-only meeting.
- How is progress reported by the recipients?

**Comment by normj** [comment]
You might think about expanding beyond .NET Foundation budget to include the requestor asking for support from the corporate sponsors. If somebody is doing a .NET gaming event they might want to see if Unity would like to particpate/support the event. Or if somebody is doing a Cloud event they might want to see if AWS would like to particpate/support the event.

**Comment by tonyqus** [comment]
Is this issue still valid?

**Comment by BethMassi** [comment]
Thanks for the ping here. I'm going to close this issue. We've been receiving proposals through the Outreach committee process: https://github.com/dotnet-foundation/wg-outreach/blob/main/proposals.md
