### ISSUE TITLE
Silk.NET: Design Meeting Community Engagement

### ISSUE THREAD

**Issue by Perksey** [dotnet-foundation/wg-marketing#8]
Hey marketing peeps 👋

Silk.NET is currently about to embark on a complete rewrite of the entire library, and is redesigning a lot of the surface API in the process. However, because of the massive amount of change, we'd like to engage the community throughout the process. In the past, we've had Discord meetings with our contributors, which have worked really well only that:
- the meetings were not recorded, so people who wanted to engage but couldn't at the time were not in the loop
- people not in our Discord server wouldn't have known they were happening
- people may have wanted to listen in on the meeting but without actively participating in conversation, and a Discord call may be discouraging for those people.

As such, the Silk.NET team would like to:
- Stream the meetings to YouTube. We currently don't have a YouTube channel, and were wondering if we could use a .NET Foundation one instead?
- Ensure the most critical meetings have proper visibility. We propose that this will be a case of us pinging someone on the marketing 
  committee closer to the time, so instructions on
      a. how to participate via Discord
      b. how to listen in via YouTube
  on the Foundation's various social channels.

Would the above be possible? Feel free to give me a shout (here or in the DNF Slack) if you would like more info!

Thanks!

<sub>cc @isaacrlevin just in case you don't get these notifications as they happen</sub>

**Comment by ddskier** [comment]
Has anyone responded to this? Wrt youtube, I think you can use the .NET Foundation youtube but I'm not sure who holds the passwords, etc. for that channel. @isaacrlevin, do you know? Wrt amplification via social, blog and email channels, we can definitely help. This repo provides info and instructions for how to get social amplification, plus inclusion in the newsletter and more: https://github.com/dotnet-foundation/content. Let me know if you need more info.

**Comment by tonyqus** [comment]
I'm researching open source marketing for a few years. Although open source projects are not commercial products, you still have to do competitor analysis in order to understand the existing market and why these components are popular so far and how they get popular. The final goal is to raise the ecosystem for your own open source project. 

Before rewriting something, I suggest you investigate the existing market of 2D/3D open source engine library.  What if your library is still not popular enough as you expected after it is rewritten. Will you give up? 

You should also investigate if the existing channels are useful or not because open source teams are usually very small (only 1-3 primary contributors). After a channel is chosen, you must put a lot of extra marketing efforts on this.

The current situation of DNF channels are as below
Youtube: 28,800 followers
Twitter: 43,000 followers
Github: Not many stars.

These information may help you judge if you should use DNF channels or create your own.

**Comment by Perksey** [comment]
> Wrt amplification via social, blog and email channels, we can definitely help. This repo provides info and instructions for how to get social amplification, plus inclusion in the newsletter and more: https://github.com/dotnet-foundation/content. Let me know if you need more info.

Awesome, thank you!

Currently, the most content-packed meeting we plan to stream (and the one in which we need the most input) has a date in the latter half of February - would that make the newsletter?

But other than that, the blog would be helpful and a Twitter post or two would be much appreciated, the details of which I'll send over (to the content repo, by the sounds of things) when they're nailed out!

I think top priority for us is just making sure we can stream to YouTube - I feel that joining a Discord server is a bigger ask than popping into a YouTube stream.

---

> you still have to do competitor analysis in order to understand the existing market and why these components are popular so far and how they get popular. 

A lot of this has gone into the proposed design of the rewrite already, and the team is always thinking about this - don't worry!

> Before rewriting something, I suggest you investigate the existing market of 2D/3D open source engine library. What if your library is still not popular enough as you expected after it is rewritten. Will you give up?

Silk.NET is quite popular today, and it is generally the de facto library for Khronos APIs these days. The reasons we're rewriting is described [here](https://github.com/dotnet/Silk.NET/blob/proposal/3.0-input/documentation/proposals/Proposal%20-%203.0%20&%203.X%20Software%20Development%20Plan.md#problems-identified-in-past-development) and the end goals [here](https://github.com/dotnet/Silk.NET/blob/proposal/3.0-input/documentation/proposals/Proposal%20-%203.0%20&%203.X%20Software%20Development%20Plan.md#goals-of-30)

This is more a rewrite for us than for the users, but as much as it is for us ultimately the users are the people we're writing a library for and as such we would like to engage the community as much as possible and get as much feedback from as many stakeholders as possible in the process. This rewrite does aim to address the problems user's have encountered in the past, after all.

So yeah, we're in a good place already at the moment, we just need to wield our existing userbase to make good decisions for what's next!

> You should also investigate if the existing channels are useful or not because open source teams are usually very small (only 1-3 primary contributors). After a channel is chosen, you must put a lot of extra marketing efforts on this.

Silk.NET has quite a following already, but pretty much only in its Discord channel and on its GitHub - there are no other channels our community so we will most likely be wanting to utilise the .NET Foundation's existing channels than try to spin-up our own.

> These information may help you judge if you should use DNF channels or create your own.

Yep, and where Silk.NET's channels fall down the .NET Foundation channels seem to shine (and vice versa) so more reason why we should use the existing channels rather than spin-up our own.

**Comment by isaacrlevin** [comment]
> Has anyone responded to this? Wrt youtube, I think you can use the .NET Foundation youtube but I'm not sure who holds the passwords, etc. for that channel. @isaacrlevin, do you know? Wrt amplification via social, blog and email channels, we can definitely help. This repo provides info and instructions for how to get social amplification, plus inclusion in the newsletter and more: [dotnet-foundation/content](https://github.com/dotnet-foundation/content). Let me know if you need more info.

For your access to YouTube, you have to be added to the YouTube channel manually, which doesn't scale REALLY well, but we can make it work. 

@Perksey do you have any planning around how you would want to use the YouTube channel? You mention one stream, but would you need ongoing streams? More than happy on figuring out a good way to amplify the work you are doing.

**Comment by Perksey** [comment]
@isaacrlevin We will likely be doing ongoing streams whenever we have designs to review, yeah; but this first one we would like to put a larger-than-usual amplification on it given the amount of designs we have to review as well as how drastically the designs will shape the future of Silk.NET. (Moreover, our hope is the most engaged viewers will engage with our other channels which will allow us to promote to that audience ourselves)

Future streams will likely just be a single tweet close to the time, and announcement via our typical channels.

Adding to the YouTube channel would be appreciated, though I appreciate it's a bit awkward! We do have a Silk.NET "team" gmail account that we can use instead if you're worried about another maintainer needing access and having to go around this loop again for the same project.

The streams are typically at 19:00 UTC, usually on a Friday. We have a date in mind for the one we're proposing here, but we're just waiting for all the core team to give it the green light before we give you that date!

**Comment by isaacrlevin** [comment]
Got it, and you want access to the YT account for ALL streams? Or just the initial? FWIW, I am going to open a Twitter poll asking what the communities thoughts on broadcasting project meetings on the Foundation YT channel.

**Comment by Perksey** [comment]
Preferably for all streams if possible, because it'd be hard to build up our own channels for this stuff. Thanks!

**Comment by Perksey** [comment]
Oh I probably should've added, the Silk.NET "team" Google account is `teamsilk.net@gmail.com`. This is probably the best one to add to the YT account.

**Comment by isaacrlevin** [comment]
Hey Dylan, the Marketing Committee chatted and we think it would be a great idea to sponsor your streams. Looking at best approach to give your live meeting creation, maybe will just add that email you shared. Give me a day to look into this

**Comment by isaacrlevin** [comment]
@Perksey I sent your Google account an email, let me know if you have any questions.

**Comment by Perksey** [comment]
Brilliant, thank you! I'll open an issue in the content repo for promotion when we're ready :D
